# Generated by Django 4.2.3 on 2023-07-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('images', models.FileField(blank=True, null=True, upload_to='zip_folders/')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
