# Generated by Django 4.2.3 on 2023-11-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/cameras/'),
        ),
    ]
