# Generated by Django 4.2.7 on 2023-11-20 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_camera_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahldorlik', models.FloatField()),
                ('behuzur', models.FloatField()),
                ('xavotir', models.FloatField()),
                ('hursandchilik', models.FloatField()),
                ('gamgin', models.FloatField()),
                ('xayron', models.FloatField()),
                ('neytral', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.URLField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mood')),
            ],
        ),
    ]
