# Generated by Django 4.2.7 on 2023-11-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mood_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='image',
            field=models.ImageField(blank=True, upload_to='./cameras/'),
        ),
    ]
