# Generated by Django 5.0 on 2023-12-04 19:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_age_alter_camera_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.employee_image_path),
        ),
    ]
