# Generated by Django 4.2.3 on 2023-07-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExistedStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('camera_url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=70)),
                ('camera_url', models.CharField(max_length=120)),
                ('happy', models.IntegerField()),
                ('sad', models.IntegerField()),
                ('angry', models.IntegerField()),
                ('neutral', models.IntegerField()),
                ('anxious', models.IntegerField()),
                ('surprise', models.IntegerField()),
                ('disguised', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=70)),
                ('camera_url', models.CharField(max_length=100)),
                ('happy', models.IntegerField()),
                ('sad', models.IntegerField()),
                ('angry', models.IntegerField()),
                ('neutral', models.IntegerField()),
                ('anxious', models.IntegerField()),
                ('surprise', models.IntegerField()),
                ('disguised', models.IntegerField()),
                ('day', models.IntegerField()),
                ('week', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='user_index')],
            },
        ),
    ]
