# Generated by Django 4.2.3 on 2023-07-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generalstatistics',
            name='user_index',
        ),
        migrations.AddIndex(
            model_name='generalstatistics',
            index=models.Index(fields=['user_id', 'happy', 'sad', 'angry', 'disguised', 'anxious', 'surprise', 'neutral'], name='indexes'),
        ),
    ]
