# Generated by Django 4.2.3 on 2023-07-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_generalstatistics_user_index_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generalstatistics',
            name='indexes',
        ),
        migrations.AddIndex(
            model_name='generalstatistics',
            index=models.Index(fields=['user_id', 'happy', 'sad', 'angry', 'disguised', 'anxious', 'surprise', 'neutral', 'day', 'week', 'month', 'year'], name='indexes'),
        ),
    ]
