# Generated by Django 4.2.3 on 2023-08-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
